swagger: '2.0'
info:
  title: OCR API
  description: OCR API documentation
  version: 1.0.0
basePath: /
schemes:
  - http
paths:
  /ocr:
    post:
      tags:
        - OCR
      summary: Perform OCR on an uploaded image
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: The image file to be processed for OCR
      responses:
        200:
          description: OCR result
          schema:
            type: object
            properties:
              ocr_result:
                type: string
        400:
          description: Error - No file part or no selected file
        404:
          description: Error - An error occurred during file processing